version: "3.8"

# Cluster Hadoop : 1 NameNode + 2 DataNodes
# Usage: docker-compose up -d

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"   # Web UI HDFS
      - "9000:9000"   # HDFS
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./data:/data
    environment:
      - CLUSTER_NAME=cluster-meteo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_replication=2
    networks:
      - hadoop-net
    restart: unless-stopped

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1-data:/hadoop/dfs/data
      - ./data:/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser=root
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net
    restart: unless-stopped

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2-data:/hadoop/dfs/data
      - ./data:/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser=root
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net
    restart: unless-stopped

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:

networks:
  hadoop-net:
    driver: bridge
